# Generated by Django 4.2.1 on 2023-05-19 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='sighting_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
